version: "3.8"

services:
  votealyze:
    build:
      context: ./votealyze
      args:
        REACT_APP_API_URL: "http://localhost:5000"
    ports:
      - "3000:80"
    restart: always

  e-stimme:
    build:
      context: ./e-stimme
      args:
        REACT_APP_API_URL: "http://localhost:5001"
    ports:
      - "3001:80"
    restart: always
