version: '3.8'

services:
  wahlergebnisse:
    image: postgres:latest
    container_name: wahlergebnisse_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wahlergebnisse
    ports:
      - "5432:5432" 
    volumes:
      - wahlergebnisse:/var/lib/postgresql/data  # Persistent storage for database data

  stimmabgabe:
    image: postgres:latest
    container_name: stimmabgabe_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stimmabgabe
    ports:
      - "5433:5432"
    volumes:
      - stimmabgabe:/var/lib/postgresql/data
      - ./scripts/db-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - keycloak-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    restart: unless-stopped
    depends_on:
      - stimmabgabe
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://stimmabgabe:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - keycloak-net
    volumes:
      - ./keycloak/portal-realm.json:/opt/keycloak/data/import/portal-realm.json
      - ./keycloak/export:/tmp/export

volumes:
  wahlergebnisse:
  stimmabgabe:

networks:
  keycloak-net:
    driver: bridge