version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bundestag_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wahldaten
    ports:
      - "5432:5432" 
    volumes:
      - ./migrations/V1__wahldaten.sql:/docker-entrypoint-initdb.d/V1__wahldaten.sql  # Load schema on startup
      - pgdata_bundestag:/var/lib/postgresql/data  # Persistent storage for database data

volumes:
  pgdata_bundestag:
