version: '3.8'

services:
  wahlergebnisse:
    image: postgres:latest
    container_name: wahlergebnisse_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wahlergebnisse
    ports:
      - "5432:5432" 
    volumes:
      - wahlergebnisse:/var/lib/postgresql/data  # Persistent storage for database data

  stimmabgabe:
    image: postgres:latest
    container_name: stimmabgabe_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stimmabgabe
    ports:
      - "5433:5432"
    volumes:
      - stimmabgabe:/var/lib/postgresql/data

volumes:
  wahlergebnisse:
  stimmabgabe: