"""update char length

Revision ID: 12f130751907
Revises: 3be85b62372d
Create Date: 2024-11-10 10:52:32.919183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f130751907'
down_revision: Union[str, None] = '3be85b62372d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Partei', 'kurzbezeichnung',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Partei', 'kurzbezeichnung',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
