"""Initial schema

Revision ID: 7dfe81c60146
Revises: 
Create Date: 2024-11-08 22:08:21.662961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfe81c60146'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Partei',
    sa.Column('parteiId', sa.Integer(), nullable=False),
    sa.Column('parteiName', sa.String(length=50), nullable=False),
    sa.Column('kurzbezeichnung', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('parteiId'),
    sa.UniqueConstraint('kurzbezeichnung'),
    sa.UniqueConstraint('parteiName')
    )
    op.create_table('Wahlkreis',
    sa.Column('wahlkreisId', sa.Integer(), nullable=False),
    sa.Column('wahlkreisName', sa.String(length=50), nullable=False),
    sa.Column('bundesland', sa.String(length=2), nullable=True),
    sa.Column('anzahlwahlberechtigte', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('wahlkreisId'),
    sa.UniqueConstraint('wahlkreisName')
    )
    op.create_table('DirektKandidat',
    sa.Column('DKId', sa.Integer(), nullable=False),
    sa.Column('DKName', sa.String(length=50), nullable=False),
    sa.Column('parteiId', sa.Integer(), nullable=True),
    sa.Column('wahlkreisId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parteiId'], ['Partei.parteiId'], ),
    sa.ForeignKeyConstraint(['wahlkreisId'], ['Wahlkreis.wahlkreisId'], ),
    sa.PrimaryKeyConstraint('DKId')
    )
    op.create_table('Ergebnisse',
    sa.Column('parteiId', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('anzahlSitze', sa.Integer(), nullable=False),
    sa.Column('direktMandate', sa.Integer(), nullable=False),
    sa.Column('ueberhangsMandate', sa.Integer(), nullable=False),
    sa.Column('ausgleichsMandate', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parteiId'], ['Partei.parteiId'], ),
    sa.PrimaryKeyConstraint('parteiId', 'jahr')
    )
    op.create_table('StimmZettel',
    sa.Column('StimmzettelId', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=True),
    sa.Column('wahlkreisId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wahlkreisId'], ['Wahlkreis.wahlkreisId'], ),
    sa.PrimaryKeyConstraint('StimmzettelId')
    )
    op.create_table('Zweitstimme',
    sa.Column('StimmzettelId', sa.Integer(), nullable=False),
    sa.Column('parteiId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parteiId'], ['Partei.parteiId'], ),
    sa.PrimaryKeyConstraint('StimmzettelId')
    )
    op.create_table('ZweitstimmeErgebnisse',
    sa.Column('parteiId', sa.Integer(), nullable=False),
    sa.Column('wahlkreisId', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('anzahlstimmen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parteiId'], ['Partei.parteiId'], ),
    sa.ForeignKeyConstraint(['wahlkreisId'], ['Wahlkreis.wahlkreisId'], ),
    sa.PrimaryKeyConstraint('parteiId', 'wahlkreisId', 'jahr')
    )
    op.create_table('Erststimme',
    sa.Column('StimmzettelId', sa.Integer(), nullable=False),
    sa.Column('kandidatId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kandidatId'], ['DirektKandidat.DKId'], ),
    sa.PrimaryKeyConstraint('StimmzettelId')
    )
    op.create_table('ErststimmeErgebnisse',
    sa.Column('kandidatId', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('anzahlstimmen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kandidatId'], ['DirektKandidat.DKId'], ),
    sa.PrimaryKeyConstraint('kandidatId', 'jahr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ErststimmeErgebnisse')
    op.drop_table('Erststimme')
    op.drop_table('ZweitstimmeErgebnisse')
    op.drop_table('Zweitstimme')
    op.drop_table('StimmZettel')
    op.drop_table('Ergebnisse')
    op.drop_table('DirektKandidat')
    op.drop_table('Wahlkreis')
    op.drop_table('Partei')
    # ### end Alembic commands ###
