"""add_geburtsjahr

Revision ID: 9be72b6c1e69
Revises: 0b44efad884d
Create Date: 2024-11-14 22:58:27.705867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be72b6c1e69'
down_revision: Union[str, None] = '0b44efad884d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Kandidat', sa.Column('geburtsjahr', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Kandidat', 'geburtsjahr')
    # ### end Alembic commands ###
