"""added more info to wahlkreise

Revision ID: bfb7b399ec84
Revises: e446236ced11
Create Date: 2024-12-22 09:36:33.824587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb7b399ec84'
down_revision: Union[str, None] = 'e446236ced11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WahlkreisInfo',
    sa.Column('wahlkreisId', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('anzahlWahlBerechtigte', sa.Integer(), nullable=False),
    sa.Column('anzahlWaehlende', sa.Integer(), nullable=False),
    sa.Column('flaeche', sa.Float(), nullable=False),
    sa.Column('bevoelkerung', sa.Float(), nullable=False),
    sa.Column('auslaender_percent', sa.Float(), nullable=False),
    sa.Column('alter_unter_18', sa.Float(), nullable=False),
    sa.Column('alter_18_24', sa.Float(), nullable=False),
    sa.Column('alter_25_34', sa.Float(), nullable=False),
    sa.Column('alter_35_59', sa.Float(), nullable=False),
    sa.Column('alter_60_74', sa.Float(), nullable=False),
    sa.Column('alter_75_mehr', sa.Float(), nullable=False),
    sa.Column('pkw_bestand', sa.Float(), nullable=False),
    sa.Column('pkw_elektro_hybrid', sa.Float(), nullable=False),
    sa.Column('bruttoinlandsprodukt', sa.Float(), nullable=False),
    sa.Column('arbeitslosenquote', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['wahlkreisId'], ['Wahlkreis.wahlkreisId'], ),
    sa.PrimaryKeyConstraint('wahlkreisId', 'jahr')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WahlkreisInfo')
    # ### end Alembic commands ###
