"""DirektKandidatenErgebnisse

Revision ID: e446236ced11
Revises: 266c600f4570
Create Date: 2024-12-19 13:50:26.984635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e446236ced11'
down_revision: Union[str, None] = '266c600f4570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Gewaehlte_direkt_kandidaten',
    sa.Column('kandidaturId', sa.Integer(), nullable=False),
    sa.Column('parteiId', sa.Integer(), nullable=True),
    sa.Column('gewonnene_stimmen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kandidaturId'], ['DirektKandidatur.kandidaturId'], ),
    sa.ForeignKeyConstraint(['parteiId'], ['Partei.parteiId'], ),
    sa.PrimaryKeyConstraint('kandidaturId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Gewaehlte_direkt_kandidaten')
    # ### end Alembic commands ###
