"""secondState

Revision ID: 50b42770040e
Revises: bbd65fb41b8d
Create Date: 2025-02-01 14:56:16.269969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b42770040e'
down_revision: Union[str, None] = 'bbd65fb41b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erststimme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kandidaturId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zweitstimme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ZSErgebnisId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zweitstimme')
    op.drop_table('erststimme')
    # ### end Alembic commands ###
