"""firstState

Revision ID: bbd65fb41b8d
Revises: 
Create Date: 2025-01-25 01:05:27.729895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd65fb41b8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validetoken',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('generiertAm', sa.DateTime(), nullable=False),
    sa.Column('gueltigBis', sa.DateTime(), nullable=True),
    sa.Column('wahlkreis', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verbrauchtetoken',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waehler',
    sa.Column('waehlerId', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('waehlerId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waehler')
    op.drop_table('verbrauchtetoken')
    op.drop_table('validetoken')
    # ### end Alembic commands ###
