@startuml

class Ergebnisse {
  + ParteiId: int
  + Jahr: int
  + AnzahlSitze: int
  + DirektMandate: int
  + UberhangMandate: int
  + AusgleichsMandate: int
}

class Erststimme {
   + id: int
   + KandidaturId : int
}


class ZweitstimmeErgebnis {
   + id: int
   + ParteiId : int
   + WahlkreisId: int
   + Jahr: int
   + AnzahlStimmen: int
}

class Zweitstimme {
   + id: int
   + ZSErgebnisId: int
}

class Wahlkreis {
  + Name: String
  + WKId: int
  + Bundesland: String
}

class WahlkreisWahlInfo {
  + WKId: int
  + Jahr: int
  + Anzahlwahlberechtigte: int
  + AnzahlWaehlende: int
}

class Bundesland {
  + Name: String
  + Kurzbezeichnung: String
}

class BundeslandStruktur {
  + Kurzbezeichnung: String
  + Jahr: int
  + Bevoelkerung: int
  + flaeche: float
}

class Kandidat {
  + KandidatId: int
  + Titel: String
  + Name: String
  + Vorname: String
  + ParteiId: int
}

class DirektKandidatur {
  + kandidaturId: int
  + KandidatId: int
  + Jahr: int
  + WahlkreisId: int
  + AnzahlStimmen: int
}

class Partei {
  + ParteiId: int
  + Name: String
  + Kurzbezeichnung: String
}

class ParteiListen {
  + ParteiId: int
  + Jahr: int
  + KandidatId: int
  + ListenPlatz: int
}



Wahlkreis " * " --> " 1 " Bundesland 

WahlkreisWahlInfo " * " --> " 1 " Wahlkreis

BundeslandStruktur " * " --> " 1 " Bundesland


ParteiListen " * " --> " 1 " Partei

ParteiListen " * " -->  " * " Kandidat

Kandidat " *  " --> " 0..1 " Partei

Kandidat " 1 " <-- " * " DirektKandidatur

DirektKandidatur " * " --> " 1 " Wahlkreis

ZweitstimmeErgebnis "  * " --> " 1 " Partei

ZweitstimmeErgebnis " * " --> " 1 " Wahlkreis


Ergebnisse  " * "  --> " * "  Partei

Erststimme " * " --> " 1 " DirektKandidatur 

Zweitstimme " * " --> " 1 " ZweitstimmeErgebnis 


@enduml